language: python

python:
  - "2.7"

os:
  - linux
  ## Python builds aren't availabe on macOS Travis
  #- osx

## The build matrix in the following stanza expands into builds for each
## OS and python version.
## Placeholder
#env:
#  global:
#    -
#  matrix:
#    -

## Add extra builds
## Placeholder
#matrix:
#  include:
#    - env:

  ## Uncomment to allow the build to report success (with non-required
  ## sub-builds continuing to run) if all required sub-builds have
  ## succeeded.  This is somewhat buggy currently: it can cause
  ## duplicate notifications and prematurely report success if a
  ## single sub-build has succeeded.  See
  ## https://github.com/travis-ci/travis-ci/issues/1696
  #fast_finish: true

  ## Careful! We use global envs, which makes it hard to exclude or
  ## allow failures by env:
  ## https://docs.travis-ci.com/user/customizing-the-build#matching-jobs-with-allow_failures
  #exclude:
    ## Placeholder
    #- python: "3.6"
    #  os: linux

## We don't need sudo. (The "apt:" stanza after this allows us to not need
## sudo; otherwise, we would need it for getting dependencies.)
sudo: false

## (Linux only) Use the latest Linux image (Ubuntu Trusty)
dist: trusty

## (Linux only) Download our dependencies
addons:
  apt:
    packages:
      ## Required dependencies
      - tor

## (OSX only) Use the default OSX image
## See https://docs.travis-ci.com/user/reference/osx#os-x-version
## Default is Xcode 9.4 on macOS 10.13 as of August 2018
#osx_image: xcode9.4

before_install:
  ## Placeholder
  -

install:
  ## Placeholder
  -
  ##
  ## Finally, list installed package versions
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dpkg-query --show; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list --versions; fi
  - python --version
  - tor --version

script:
  - tools/test-network.sh

after_failure:
  ## Re-run chutney in debug mode
  ## TODO: improve debug mode
  - tools/test-network.sh --debug

after_success:
  ## Placeholder
  -

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-ci"
    template:
      - "%{repository} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build #%{build_number} %{result}. Details: %{build_url}"
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: change
